### ISSUE TITLE
Hindi Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-hi#1]
## Maintainer List

* @sakshamtaneja21 
* @SatyaRF 
* @arshadkazmi42

## For New Translators

To translate a page:38

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, please read the [translation guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) and [contribution guide](https://github.com/gatsbyjs/gatsby-hi/blob/master/contibuting.md)  to understand the Gatsby translation process.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Home

* [ ] README.md
* [x] contributing.md (@arshadkazmi42 ) #5  
* [ ] style-guide.md (@satyamtg )

### Community

* [x] community/code-of-conduct (@arshadkazmi42 ) #5 ✅ 
    

### Tutorial

* [x] tutorial/index (@SatyaRF ) #7 ✅ 
* [ ] tutorial/part-zero (@helios1101 ) #14 ✏️
* [x] tutorial/part-one (@NileshPatel17 ) #19 ✅ 
* [x] tutorial/part-two (@NileshPatel17 ) #12 ✅ 
* [x] tutorial/part-three (@KiranAkadas ) #17 ✅ 
* [x] tutorial/part-four (@NileshPatel17 ) #20 ✅ 
* [x] tutorial/part-five (@KiranAkadas ) #13 ✅ 
* [x] tutorial/part-six (@NileshPatel17 ) #24 ✅ 
* [x] tutorial/part-seven (@NileshPatel17 ) #25 ✅ 
* [x] tutorial/part-eight (@monizb) #21 ✅
    

### Docs

* [ ] accessibility-statement (@spielers ) #37 🏃
* [ ] docs/ab-testing-with-google-analytics-and-netlify.md 
* [x] docs/ab-testing.md (@Aayush-1999 ) #58 ✅ 
* [x] docs/actions.md (@noisefilter19 ) #54 ✅ 
* [ ] docs/add-custom-webpack-config.md (@Pluto-fox )
* [ ] docs/add-offline-support-with-a-service-worker.md (@abhay-ranawat )
* [ ] docs/add-page-metadata.md (@Aayush-1999 )
* [ ] docs/add-seo-component.md (@Leonidas328 )
* [ ] docs/adding-a-list-of-markdown-blog-posts.md (@kaioshin20 )
* [x] docs/adding-an-rss-feed.md
* [ ] docs/adding-analytics.md (@tanishqchamola )
* [ ] docs/adding-app-and-website-functionality.md
* [ ] docs/adding-comments.md (@sushant-varanasi )
* [ ] docs/adding-forms.md (@imrishabh18 )
* [ ] docs/adding-markdown-pages.md
* [ ] docs/adding-tags-and-categories-to-blog-posts.md
* [x ] docs/adding-search.md (@kaioshin20 ) ✅ 
* [] docs/adding-search-with-js-search.md
* [ ] docs/adding-search-with-algolia.md
* [ ] docs/adding-react-components.md (@BhuvanChandra )
* [ ] docs/adding-pagination.md (@therenujoshi )
* [ ] docs/adding-page-transitions-with-plugin-transition-link.md
* [ ] docs/api-proxy.md (@rjn01 )
* [x] docs/api-files.md (@khanBilal167  ) #61 ✅ 
* [ ] docs/api-files-gatsby-ssr.md
* [x] docs/api-files-gatsby-node.md (@noisefilter19 ) #55  ✅ 
* [ ] docs/api-files-gatsby-config.md (@monishbb )
* [ ] docs/api-files-gatsby-browser.md (@KillMonger1 )
* [x] docs/answering-it-security.md (@krahul32 ) #62 ✅
* [ ] docs/api-specification.md (@syshcndr )
* [x] docs/add-404-page (@spielers ) #31 ✅
* [ ] docs/add-a-manifest-file (@spielers ) #39  🏃 
* [x] docs/add-a-service-worker (@spielers ) #40 ✅
* [x] docs/adding-page-transitions (@KillMonger1 ) #35 ✅ 
* [x] docs/index (@mrmakadia94 ) #10 ✅ 
* [x] docs/quick-start (@akramkazmi71 ) #9 ✅ 
* [ ] docs/recipes (@spielers ) 
* [x] docs/gatsby-cli (@NileshPatel17 ) #11 ✅ 
* [x] docs/basic-hardware-software-requirements (@Yashakad ) #42 ✅ 
* [x] docs/best-practices-for-orgs (@KillMonger1 ) #46 ✅ 
* [ ] docs/building-a-blog (@shreenidhikulkarni25 ) #52 ✅
* [x] docs/building-a-site-with-asynchronous-data (@ShubhaIn ) #49 ✅
* [x] docs/v1-release-notes (@akramkazmi71 ) #33 ✅ 
* [x] docs/glamor (@akramkazmi71 ) #32 ✅ 
* [x] docs/plugins.md (@KillMonger1 ) #38 ✅  

### Contributing

* [x] docs/contributing/index (@monizb ) #23 ✅
* [x] docs/contributing/how-to-contribute (@SunitaBhat101 ) #34 ✅
* [x] docs/contributing/how-to-file-an-issue (@KillMonger1 ) #29 ✅
* [ ] docs/contributing/how-to-label-an-issue (@prateekpardeshi ) #41 ✏️

### Legends

✅ Completed
✏️ In Review
🏃 Waiting for review

**Comment by akramkazmi71** [comment]
I would like to translate docs/quick-start

**Comment by arshadkazmi42** [comment]
> I would like to translate docs/quick-start

Assigned your name to the page

**Comment by helios1101** [comment]
I would like to translate tutorial/part-zero. Can I take the same?

**Comment by arshadkazmi42** [comment]
@helios1101 Go a ahead. I will assign your name to the page

**Comment by NileshPatel17** [comment]
PR #11 created for ```docs/gatsby-cli```

**Comment by NileshPatel17** [comment]
PR #12 created for ```tutorial/part-two```

**Comment by arshadkazmi42** [comment]
> PR #12 created for `tutorial/part-two`

Please send new PRs after closing already open ones. You can send PRs for new pages on #11 is merged.

**Comment by KiranAkadas** [comment]
I'll take up part-five

**Comment by arshadkazmi42** [comment]
@KiranAkadas Cool. Go ahead.

**Comment by KiranAkadas** [comment]
I'll take part-three next if that's ok.

**Comment by arshadkazmi42** [comment]
Sure go ahead

**Comment by NileshPatel17** [comment]
@arshadkazmi42 shall i resume working on #12

**Comment by arshadkazmi42** [comment]
Yes, pease go ahead. #11 is merged.

**Comment by NileshPatel17** [comment]
shall i take ```tutorial/part-one```

**Comment by arshadkazmi42** [comment]
@NileshPatel17 Sure, go ahead

**Comment by NileshPatel17** [comment]
tutorial/part-one #19 is ready to be review

**Comment by NileshPatel17** [comment]
```tutorial/part-four``` is almost translated, and would be submitting PR today evening.

**Comment by arshadkazmi42** [comment]
@NileshPatel17 Cool. I will assign your name to the page.

**Comment by NileshPatel17** [comment]
PR #20 submitted for ```tutorial/part-four```

**Comment by monizb** [comment]
I would like to take tutorial/part-eight

**Comment by arshadkazmi42** [comment]
cool. I think, we mark X to the page when its translated and merged

**Comment by NileshPatel17** [comment]
Both ``` tutorial/part-six``` and ``` tutorial/part-seven``` are almost translated, and would be ready for review. Let me know when i shall create new PR.

**Comment by monizb** [comment]
> cool. I think, we mark X to the page when its translated and merged

Hey! Sorry I didn't know about that, I thought once it's assigned it's ticked I have removed it now 😀 also I have created a PR for the Part 8 translation, thanks!

**Comment by monizb** [comment]
> Both ` tutorial/part-six` and ` tutorial/part-seven` are almost translated, and would be ready for review. Let me know when i shall create new PR.

@NileshPatel17 
Hey, whenever you are ready, you can create a PR for ` tutorial/part-six` , meanwhile i have also assigned your name to both the pages.

**Comment by arshadkazmi42** [comment]
@monizb Removed your name from `docs/glossary` as you already have two PR open. 
Let's keep the pages open for other contributors

You can take it up, once current PRs are merged

**Comment by arshadkazmi42** [comment]
@NileshPatel17 Have you started working on `tutorial/part-seven` as your name is assigned to it?

We will remove your name and keep the pages available for other contributors, since you are already working on another page which has open PR

**Comment by NileshPatel17** [comment]
@arshadkazmi42 ```tutorial/part-seven``` is completed. shall a create PR?

**Comment by arshadkazmi42** [comment]
> @arshad tutorial/part-seven is completed. shall a create PR?

@NileshPatel17 Yes. Let's get all the PRs in. So to have tracked. We will review that once the current active PRs are closed.

**Comment by spielers** [comment]
is there any remaining translation pages required I will love to do so, is the docs/recipes are remaining to get translated  ??

**Comment by arshadkazmi42** [comment]
@spielers we have few pending pages

docs/recipes
docs/glossary

you could take up any of those. once we are done with current list,  we will update more pages. There are alot of pages which needs to be translated. We are working in phases to translate all of them

**Comment by spielers** [comment]
@arshadkazmi42 I am translating docs/recipes

**Comment by arshadkazmi42** [comment]
Hey everyone,
I have updated the pages list to which are pending to translate.
If anyone is looking for contribution, you can pick any page from the list and can start working on it 👍

**Comment by KillMonger1** [comment]
Will take up /how-to-file-an-issue.md.

**Comment by arshadkazmi42** [comment]
> Will take up /how-to-file-an-issue.md.

Cool. go ahead

**Comment by the-coder-dude** [comment]
@arshadkazmi42   I would take "docs/contributing/how-to-label-an-issue.md" 🙂

**Comment by spielers** [comment]
@arshadkazmi42 i translated page-404-page.md
Please merge that

**Comment by arshadkazmi42** [comment]
@prateekpardeshi Cool. Go ahead. I will assign  your name

**Comment by arshadkazmi42** [comment]
@spielers Sure will do. I am bit busy. I will have to do a high level review again just to check nothing else has broken.

**Comment by spielers** [comment]
Cool

**Comment by praisonjoshua** [comment]
i am a noob here, this is my first attempt to contribute in github, please help me out. which page how should i choose

**Comment by arshadkazmi42** [comment]
Hey @praisonjoshua 
Take any page, translation with be same and we are here to help.

**Comment by spielers** [comment]
@arshadkazmi42 I will start working on docs/recipes, just merge the page-404 sir please.

**Comment by arshadkazmi42** [comment]
@spielers added some review on 404 page. Let's get those fixed and then you can start working on docs/recipes

**Comment by SunitaBhat101** [comment]
Hello,
Can i take up how-to-contribute.md ?

**Comment by arshadkazmi42** [comment]
@SunitaBhat101 Go ahead. I will assign your name to page

**Comment by KillMonger1** [comment]
@arshadkazmi42 I've made all changes to my previous PR. I'll proceed with  docs/adding-page-transitions

**Comment by KillMonger1** [comment]
Going with docs/plugin.md

**Comment by spielers** [comment]
can I start working on this accessibility-statement.md

**Comment by spielers** [comment]
accessibility-statement.md completed

**Comment by spielers** [comment]
this both are small pages so I translated both of them and made a different prs for each of the following 
1]docs/add-a-manifest-file
2]docs/add-a-service-worker

**Comment by the-coder-dude** [comment]
@arshadkazmi42 Created a PR for how-to-label-an-issue.md . Please have a look at it  #41

**Comment by KillMonger1** [comment]
@arshadkazmi42 I'll be working on docs/adding-website-functionality. I'll post the PR after my previous PR is merged.

**Comment by Yashakad** [comment]
Hello
I'll work on docs/basic-hardware-software-requirements.

**Comment by arshadkazmi42** [comment]
> basic-hardware-software-req

@Yashakad cool go ahead.

**Comment by arshadkazmi42** [comment]
@KiranAkadas 
any specific reason for "unpinning" this issue?

**Comment by KiranAkadas** [comment]
Hey
Really sorry. It happened by mistake, i didn't mean to do that.

**Comment by arshadkazmi42** [comment]
> Hey
> Really sorry. It happened by mistake, i didn't mean to do that.

no issues. just wanted to cross check 👍

**Comment by spielers** [comment]
@arshadkazmi42 I wanted to be a code reviewer can I?? 
I will try to give my 100 % for this work

**Comment by Yashakad** [comment]
@arshadkazmi42 PR is up for basic-hardware-software-req.md

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 I wanted to be a code reviewer can I??
> I will try to give my 100 % for this work

@spielers sure. I am looking for more reviewers.
Do you have any previous experience with translation reviews?

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 PR is up for basic-hardware-software-req.md

thanks. I will get to it soon

**Comment by spielers** [comment]
@arshadkazmi42 I translated a book of VIT local chapter in 2 languages Hindi and Marathi
and started contributing for open source.

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 I translated a book of VIT local chapter in 2 languages Hindi and Marathi
> and started contributing for open source.

cool. can you pick one open PR and start reviewing. 
you can do first review and i can do second review.
after some time we can continue review separately

**Comment by spielers** [comment]
cool then ill start reviewing now

**Comment by KillMonger1** [comment]
Taking up docs/best-practices-for-orgs.md

**Comment by KillMonger1** [comment]
@arshadkazmi42 Please review the pending PR.

**Comment by ShubhaIn** [comment]
Hello! Can i take up  docs/building-a-site-with-asynchronous-data

**Comment by shreenidhikulkarni25** [comment]
I'm a newbie
I'll work on building-a-blog.md

**Comment by noisefilter19** [comment]
Hello! I'll work on this small page  docs/api-reference

**Comment by arshadkazmi42** [comment]
> Hello! I'll work on this small page docs/api-reference

cool. go ahead

**Comment by noisefilter19** [comment]
Taking up browser-apis

**Comment by arshadkazmi42** [comment]
@noisefilter19 please pick pages which are listed in the issue.
I have updated the list. Please refresh page to see latest list

**Comment by noisefilter19** [comment]
Ok then actions.md

**Comment by noisefilter19** [comment]
I'll take docs/api-files-gatsby-node.md next

**Comment by arshadkazmi42** [comment]
@noisefilter19 let's get all your open PRs merged first, before you send any new PRs

**Comment by noisefilter19** [comment]
Ok. I've made the required changes to my previous PR

**Comment by Aayush-1999** [comment]
I would like to translate docs/ab-testing.md

**Comment by arshadkazmi42** [comment]
@Aayush-1999 go ahead

**Comment by imrishabh18** [comment]
Hey, assign me docs/adding-forms.md

**Comment by arshadkazmi42** [comment]
> Hey, assign me docs/adding-forms.md

page assigned.

**Comment by kaioshin20** [comment]
I would like to translate docs/adding-search.md

**Comment by arshadkazmi42** [comment]
> I would like to translate docs/adding-search.md

page assigned

**Comment by khanBilal167** [comment]
I would like to take docs/api-files.md

**Comment by arshadkazmi42** [comment]
> I would like to take docs/api-files.md

page assigned

**Comment by krahul32** [comment]
Hi! I'll be taking *docs/answering-it-security.md* now

**Comment by krahul32** [comment]
Now taking `docs/api-files-gatsby-node.md`.

**Comment by krahul32** [comment]
Now taking `docs/api-files-gatsby-ssr.md`.

**Comment by krahul32** [comment]
Hello, @arshadkazmi42  I created the PR, review this. 
`docs/answering-it-security.md`

**Comment by khanBilal167** [comment]
> 
> 
> > I would like to take docs/api-files.md
> 
> page assigned

Done can you please review it.

**Comment by noisefilter19** [comment]
I'll take up docs/api-files-gatsby-node.md
#64

**Comment by krahul32** [comment]
I'll Take `docs/api-files-gatsby-browser.md`

**Comment by satyamtg** [comment]
Hey, I translated style-guide.md. See #65

**Comment by sushant-varanasi** [comment]
I would like to translate docs/adding-comments.md

**Comment by kaioshin20** [comment]
I would like to translate docs/adding-a-list-of-markdown-blog-posts.md

**Comment by Aayush-1999** [comment]
I would like to translate docs/add-page-metadata.md

**Comment by therenujoshi** [comment]
I would like to translate docs/adding-pagination.md

**Comment by KillMonger1** [comment]
I'll take up api-files-gatsby-browser.md

**Comment by BhuwanChandra** [comment]
Hey @arshadkazmi42, I would like to translate `docs/adding-react-components.md`. assign this to me.

**Comment by syshcndr** [comment]
Hey @arshadkazmi42 
I am interested in translating docs/api-specification.md.
Can you assign this to me.

**Comment by spielers** [comment]
@syshcndr You can take any pages that are remaining in the list and send PR

**Comment by rjn01** [comment]
Hey, @arshadkazmi42 
I would like to work on  docs/api-proxy.md . Can you assign me?

**Comment by arshadkazmi42** [comment]
hey guys. sorry for late replies. please go ahaead take the pages which are not assign to anyone.
i will be updating the assigned pages list ASAP.

**Comment by arshadkazmi42** [comment]
assigned names to pages for all the above comments. please start working on ot and send PR. Happy Hacktoberfest 🤘

**Comment by Leonidas328** [comment]
I'll be translating docs/add-seo-component.md.

**Comment by arshadkazmi42** [comment]
> I'll be translating docs/add-seo-component.md.

@Leonidas328 page assigned

**Comment by Pluto-fox** [comment]
Hey I Would like to do docs/add-custom-webpack-config.md

**Comment by abhay-ranawat** [comment]
I Want to Translate docs/add-offline-support-with-a-service-worker.md  @arshadkazmi42

**Comment by kaioshin20** [comment]
Hi @arshadkazmi42 I submitted my pr and can you add "hacktoberfest-accepted" label to my pr or add "hacktoberfest" topic to this repository ? It would be a great help !

https://github.com/gatsbyjs/gatsby-hi/pull/71

**Comment by ghost** [comment]
@arshadkazmi42  can I take  docs/api-files-gatsby-config.md?

**Comment by tanishqchamola** [comment]
@sakshamtaneja21 
@SatyaRF 
@arshadkazmi42 
Hi, I would like to translate docs/adding-analytics.md

**Comment by arshadkazmi42** [comment]
> Hey I Would like to do docs/add-custom-webpack-config.md

page assigned

**Comment by arshadkazmi42** [comment]
> Hey I Would like to do docs/add-custom-webpack-config.md

page assigned

**Comment by arshadkazmi42** [comment]
> Hi @arshadkazmi42 I submitted my pr and can you add "hacktoberfest-accepted" label to my pr or add "hacktoberfest" topic to this repository ? It would be a great help !
> 
> #71

added label

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 can I take docs/api-files-gatsby-config.md?

page assigned

**Comment by arshadkazmi42** [comment]
> @sakshamtaneja21
> @SatyaRF
> @arshadkazmi42
> Hi, I would like to translate docs/adding-analytics.md

page assigned

**Comment by abhay-ranawat** [comment]
> I Want to Translate docs/add-offline-support-with-a-service-worker.md @arshadkazmi42

Hey Assign me @arshadkazmi42

**Comment by sushant-varanasi** [comment]
> I would like to translate docs/adding-comments.md

I had created a pull request for the same,but no one has gone through it. Can someone go through PR #66 and review it.

**Comment by arshadkazmi42** [comment]
> > I would like to translate docs/adding-comments.md
> 
> I had created a pull request for the same,but no one has gone through it. Can someone go through PR #66 and review it.

I have been a bit busy lately. will review it as soon as possible. Thank you for your patience.

**Comment by ivaibhavjindal** [comment]
Hi @arshadkazmi42! I'd like to translate `docs/api-files-gatsby-ssr.md`. Can you please assign it to me?

**Comment by Aashrut** [comment]
Hi, @sakshamtaneja21
@SatyaRF
@arshadkazmi42
I would like to translate `docs/ab-testing-with-google-analytics-and-netlify.md`. Can you assign it to me?

**Comment by amnindersingh12** [comment]
Hi @arshadkazmi42i, I would like to translate  _docs/api-files-gatsby-ssr.md_ 
**Please assign it to me.**

**Comment by amnindersingh12** [comment]
I had created a pull request for the same, but no one has gone through it. Can someone go through PR #75 and review it.

**Comment by HoneyBadger151** [comment]
Hi, @sakshamtaneja21 @SatyaRF @arshadkazmi42 
I would like to translate docs/adding-page-transitions-with-plugin-transition-link.md
Please assign it to me

**Comment by Rutam21** [comment]
Hello, @sakshamtaneja21 @SatyaRF @arshadkazmi42 I would like to translate `docs/adding-an-rss-feed.md`. Please assign the page to me.
